workflows:
  android-build:
    name: Flutter Android Build
    instance_type: linux_x2
    max_build_duration: 30
    environment:
      vars:
        FLUTTER_VERSION: "3.13.0"
    triggering:
      events:
        - push
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --split-per-abi
    artifacts:
      - build/app/outputs/**/*.apk
